import React, { useState, useEffect } from 'react';
import { supabase } from '../../services/supabase';

const ReceiptApprovals = () => {
  const [pendingReceipts, setPendingReceipts] = useState([]);
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState('');
  const [error, setError] = useState('');

  useEffect(() => {
    fetchPendingReceipts();
  }, []);

  const fetchPendingReceipts = async () => {
    setLoading(true);
    setError('');
    const { data, error } = await supabase
      .from('receipts')
      .select(`
        *,
        order:order_id(
          id,
          total_amount,
          created_at,
          client_id,
          client:client_id(full_name, email, contact_number),
          order_items(
            product:product_id(name, price),
            quantity,
            subtotal
          )
        ),
        employee:generated_by(full_name, email)
      `)
      .eq('is_approved', false)
      .order('generated_at', { ascending: true });
    
    if (!error) {
      setPendingReceipts(data || []);
    } else {
      setError('Failed to load receipts: ' + error.message);
    }
    setLoading(false);
  };

  const handleApprove = async (receiptId, orderId) => {
    setSuccess('');
    setError('');
    
    try {
      // Update receipt
      const { error: receiptError } = await supabase
        .from('receipts')
        .update({ 
          is_approved: true, 
          approved_at: new Date().toISOString(),
          sent_to_client: true  // ✅ This is already here - good!
        })
        .eq('id', receiptId);
      
      if (receiptError) throw receiptError;

      // Update order
      const { error: orderError } = await supabase
        .from('orders')
        .update({ 
          admin_approved: true,
          status: 'approved'
        })
        .eq('id', orderId);
      
      if (orderError) throw orderError;

      setSuccess('✅ Receipt approved and sent to client!');
      fetchPendingReceipts();
      
      // Clear success after 3 seconds
      setTimeout(() => setSuccess(''), 3000);
    } catch (err) {
      setError('Error approving receipt: ' + err.message);
      setTimeout(() => setError(''), 3000);
    }
  };

  const handleReject = async (receiptId, orderId) => {
    if (!window.confirm('Reject this receipt?')) return;
    
    setSuccess('');
    setError('');
    
    try {
      const { error } = await supabase
        .from('receipts')
        .delete()
        .eq('id', receiptId);
      
      if (error) throw error;
      
      // Update order status
      await supabase
        .from('orders')
        .update({ status: 'cancelled' })
        .eq('id', orderId);
      
      setSuccess('✅ Receipt rejected.');
      fetchPendingReceipts();
      setTimeout(() => setSuccess(''), 3000);
    } catch (err) {
      setError('Error rejecting receipt: ' + err.message);
      setTimeout(() => setError(''), 3000);
    }
  };

  return (
    <div>
      <h2 className="text-2xl font-bold mb-4">🧾 Receipt Approvals</h2>
      <p className="text-gray-600 mb-4">Review and approve receipts generated by employees.</p>

      {success && (
        <div className="mb-4 p-3 bg-green-100 text-green-700 rounded-lg text-sm">
          {success}
        </div>
      )}
      
      {error && (
        <div className="mb-4 p-3 bg-red-100 text-red-700 rounded-lg text-sm">
          {error}
        </div>
      )}

      {loading ? (
        <div className="text-center py-8">Loading...</div>
      ) : pendingReceipts.length === 0 ? (
        <div className="text-center py-8 text-gray-500">
          ✅ No pending receipt approvals.
        </div>
      ) : (
        <div className="space-y-4">
          {pendingReceipts.map((receipt) => (
            <div key={receipt.id} className="border rounded-lg p-4 hover:bg-gray-50">
              <div className="flex flex-col md:flex-row justify-between">
                <div className="flex-1">
                  <div className="flex items-center space-x-4">
                    <p className="font-semibold text-lg">Receipt #{receipt.receipt_number}</p>
                    <span className="text-sm bg-yellow-100 text-yellow-700 px-2 py-1 rounded">
                      ⏳ Pending
                    </span>
                  </div>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-2 mt-2">
                    <div>
                      <p className="text-sm text-gray-600">👤 Client: <span className="font-medium">{receipt.order?.client?.full_name || 'N/A'}</span></p>
                      <p className="text-sm text-gray-600">📧 Email: {receipt.order?.client?.email || 'N/A'}</p>
                      <p className="text-sm text-gray-600">📞 Contact: {receipt.order?.client?.contact_number || 'N/A'}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-600">👨‍💼 Generated by: {receipt.employee?.full_name || 'N/A'}</p>
                      <p className="text-sm text-gray-600">📅 Date: {new Date(receipt.generated_at).toLocaleString()}</p>
                      <p className="text-sm font-bold text-green-600">💰 Total: ₱{receipt.order?.total_amount?.toFixed(2) || '0.00'}</p>
                    </div>
                  </div>

                  {/* Items Summary */}
                  <div className="mt-2">
                    <p className="text-sm font-medium text-gray-700">Items:</p>
                    <div className="flex flex-wrap gap-2 mt-1">
                      {receipt.order?.order_items?.map((item, idx) => (
                        <span key={idx} className="text-xs bg-gray-100 px-2 py-1 rounded">
                          {item.product?.name} × {item.quantity} = ₱{item.subtotal?.toFixed(2)}
                        </span>
                      ))}
                    </div>
                  </div>
                </div>
                
                <div className="flex flex-col space-y-2 mt-4 md:mt-0 md:ml-4">
                  <button
                    onClick={() => handleApprove(receipt.id, receipt.order_id)}
                    className="bg-green-500 text-white px-6 py-2 rounded hover:bg-green-600 transition"
                  >
                    ✅ Approve
                  </button>
                  <button
                    onClick={() => handleReject(receipt.id, receipt.order_id)}
                    className="bg-red-500 text-white px-6 py-2 rounded hover:bg-red-600 transition"
                  >
                    ❌ Reject
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default ReceiptApprovals;